# Generated by Django 4.0.3 on 2022-05-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('delete_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('delete_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('bank_account_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer', to='accountbook.bankaccount')),
                ('bank_account_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payee', to='accountbook.bankaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pastime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('delete_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('delete_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('delete_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usecase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('delete_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('delete_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('store_name', models.CharField(max_length=30)),
                ('item_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('payment_month', models.DateField(null=True)),
                ('note', models.CharField(max_length=30, null=True)),
                ('points', models.IntegerField(null=True)),
                ('billing_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accountbook.billingmethod')),
                ('pastime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accountbook.pastime')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accountbook.person')),
                ('usecase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accountbook.usecase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='billingmethod',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accountbook.paymentmethod'),
        ),
    ]
